apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-lib
spec:
  selector:
    matchLabels:
      app: central-lib
  template:
    metadata:
      labels:
        app: central-lib
    spec:
      initContainers:
      - name: central-db
        image: postgres
        ports:
          - containerPort: 5432
        envFrom:
          - configMapRef:
              name: central-db-config
        volumeMounts: 
          - mountPath: /var/lib/postgresql/data
            name: central-db-vol
        command: ['sh', '-c', 
          'until pg_isready -h central-db -p 5432; 
          do echo waiting for database; sleep 1; done;']

      containers:
      - name: central
        image: fstefanov/cc-projekat:central
        ports:  
          - containerPort: 80

      volumes: 
        - name: central-db-vol
          persistentVolumeClaim:
            claimName: central-db-pvc
