FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["./LocalLib/LocalLib.csproj", "./"]
RUN dotnet restore "LocalLib.csproj"
COPY ./LocalLib .
WORKDIR "/src/"
RUN dotnet build "LocalLib.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "LocalLib.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV CENTRAL_HOST=central
ENTRYPOINT ["dotnet", "LocalLib.dll"]
