apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: library-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: lib-ingress
    http:
      paths:
      - path: /local-ns(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: local-ns-service
            port:
              number: 80
      - path: /local-bg(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: local-bg-service
            port:
              number: 80
      - path: /local-nis(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: local-nis-service
            port:
              number: 80
