apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: local
        image: fstefanov/cc-projekat:local
        imagePullPolicy: Always
        env: 
        - name: DB_HOST
          value: "localhost"
        - name: CENTRAL_HOST
          value: central-lib-service.default
        ports:  
          - containerPort: 80

      - name: local-db
        image: postgres
        ports:
          - containerPort: 5432
        envFrom:
          - configMapRef:
              name: local-db-config
        volumeMounts: 
          - mountPath: /var/lib/postgresql/data
            name: local-vol

      volumes: 
        - name: local-vol
          persistentVolumeClaim:
            claimName: {{ .Values.pvc }}
