name: Build and push to DockerHub
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Docker login
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build and push central lib. image
      run: |
        docker build ./CentralLib --file Dockerfile --tag fstefanov/cc-projekat:central
        docker push fstefanov/cc-projekat:central
    - name: Build and push local lib. image
      run: |
        docker build ./LocalLib --file Dockerfile --tag fstefanov/cc-projekat:local
        docker push fstefanov/cc-projekat:local
